### ISSUE TITLE
unclear inputs for tool.jar

### ISSUE THREAD

**Issue by quizzo** [karimhamdanali/averroes#1]
When using tool.jar 
 java -jar tool.jar <absolute_path_to_doop_home> <tool_name> <base> <benchmark> <isAverroes>

It is unclear what are the needed outputs for wala. In addition, if one would like to include this jar in an eclipse project, it is unclear what methods should be called to generate a call graph from it.

The following averroes jars are available 
averroes-lib-class.jar
organized-app.jar
organized-lib.jar
placeholder-lib.jar

it is clear that the tool_name is wala, and isAverroes is true, but it is not clear what should be the absolute path, base and benchmark.

**Comment by karimhamdanali** [comment]
Hi quizzo,

The classes in averroes-experiments are created specifically to run the DaCapo and SPECJVM benchmark suites and might not necessarily be useful for generic use.

In general, tool.jar needs the following parameters (more documentation can be found here https://github.com/karimhamdanali/averroes-experiments/blob/master/src/averroes/experiments/options/ExperimentsOptions.java):
- -h: DOOP home directory (just provide any string here since it won't be used by WALA)
- -t: wall
- -b: base directory where those input JAR files are (could simply be ".")
- -p: benchmark directory (the parent directory holding the input JAR files inside the base directory, so the path would be base/benchmark/averroes-lib-class.jar)
- -a: use averroes
- -j: (JRE version for DOOP, doesn't matter for WALA, put 1.6 for example)
- -r: application regex (what classes/packages are part of the application code)
- -m: main class
- -d: dynamic classes file (supply an empty file as this is specific to Soot)
- -o: output directory

If you like to build your own CallGraphFactory, you can find more information about this in the method CallGraphFactory.generateWalaCallGraph() here https://github.com/karimhamdanali/averroes-experiments/blob/master/src/averroes/experiments/CallGraphFactory.java#L101

But in general, WALA needs the following:
-  placeholder-lib.jar loaded in the Primordial loader
- averroes-lib-class.jar and organized-app.jar loaded in the Application loader (see https://github.com/karimhamdanali/averroes-experiments/blob/master/src/averroes/experiments/CallGraphFactory.java#L153)
- need to set up entry points such that it includes the averroes.Library.<clinit> in addition to any main method your application has (see https://github.com/karimhamdanali/averroes-experiments/blob/master/src/averroes/experiments/CallGraphFactory.java#L173)
- disable reflection by calling options.setReflectionOptions(ReflectionOptions.NONE)
- disable WALA's handling of zero-length arrays by calling options.setHandleZeroLengthArray(false); (might not be in the master WALA branch yet)
- do not add any bypass logic to the method/class selectors (see https://github.com/karimhamdanali/averroes-experiments/blob/master/src/averroes/experiments/CallGraphFactory.java#L138)
